### ISSUE TITLE
Doesn't generate correct html on nuxt generate

### ISSUE THREAD

**Issue by frixou89** [gehrj/vue-country-region-select#24]
I'm using this plugin with nuxt. In development it looks fine, However, when I generate static files with `nuxt generate` the html tag stays as `<country-select></<country-select>`. It should be generated into a `<select>` tag instead.

**Comment by gehrj** [comment]
@frixou89 I am not too familiar with nuxt. I can try and look into this. Have you found a solution since posting this?

**Comment by gehrj** [comment]
@frixou89 I can not be sure without knowing how you are using exactly with nuxt but it looks like there may be issues using vue plugins if ssr is not set to false and also making sure to load in vendor file. You may already be doing this but this is what I found.  I will link the article. The part I found that sounds related to this issue is at the bottom.

https://medium.com/@codebeast_/why-your-third-party-plugin-dont-work-in-nuxt-and-how-to-fix-it-d1a8caadf422

**Comment by frixou89** [comment]
I just had to use it with `mode: 'client'` in `nuxt.config.js` so it's rendered only on the client side

```js
  plugins: [
  ...
    { src: '~/plugins/vue-country-region-select.js', mode: 'client' }
  ],
```

**Comment by coreysyms** [comment]
Old thread but this was driving me crazy. In Nuxt.js dynamic site, not static requires BOTH
```
plugins: [
  ...
    { src: '~/plugins/vue-country-region-select.js', mode: 'client' }
  ],
```
AND wrapping your `<country-select>` in `<no-ssr>` tags
