### ISSUE TITLE
countryName property not working

### ISSUE THREAD

**Issue by yaodev778** [gehrj/vue-country-region-select#9]
when I set countryName props with true, it output errors in console.

Error in render: "TypeError: Cannot read property 'countryName' of undefined"

**Comment by gehrj** [comment]
@yaodev778 Thanks for finding this! It should now be fixed in recent update!

**Comment by gehrj** [comment]
@yaodev778 I agree that it is not so obvious currently that this is required when using countryName, I will change the README to better reflect this for now. I will also look into creating a better way to autodetect this error and correct it for the user if possible! 

I appreciate your input and hope you are enjoying the component otherwise!
